src/main/java/org/example/mjuteam4/comment/CommentController.java, src/main/java/org/example/mjuteam4/commentLike/CommentLikeController.java, src/main/java/org/example/mjuteam4/commentLike/dto/response/CommentLikeTotalResponse.java, src/main/java/org/example/mjuteam4/global/exception/ExceptionCode.java, src/main/java/org/example/mjuteam4/member/entity/Member.java, src/main/java/org/example/mjuteam4/tradePost/TradePostController.java, src/main/java/org/example/mjuteam4/tradePost/TradePostRepository.java, src/main/java/org/example/mjuteam4/tradePost/TradePostService.java, src/main/java/org/example/mjuteam4/tradePost/dto/request/TradePostRequest.java, src/main/java/org/example/mjuteam4/tradePost/dto/response/TradePostResponse.java, src/main/java/org/example/mjuteam4/tradePost/entity/TradePost.java, src/main/java/org/example/mjuteam4/tradePost/exception/TradePostNotFound.java, src/main/java/org/example/mjuteam4/tradePostImage/TradePostImageRepository.java, src/main/java/org/example/mjuteam4/tradePostImage/TradePostImageService.java, src/main/java/org/example/mjuteam4/tradePostImage/entity/TradePostImage.java
#10
어떤 변경 사항이 있나요?
거래 게시판 기능을 완성했습니다.
질문 게시판이랑 비슷한 내용입니다.
=> [#10] 거래 게시판

src/main/java/org/example/mjuteam4/question/QuestionController.java, src/main/java/org/example/mjuteam4/question/QuestionService.java, src/main/java/org/example/mjuteam4/question/dto/request/QuestionCreateRequest.java, src/main/java/org/example/mjuteam4/question/dto/request/QuestionUpdateRequest.java, src/main/java/org/example/mjuteam4/question/entity/Question.java, src/main/java/org/example/mjuteam4/questionImage/QuestionImageService.java, src/main/java/org/example/mjuteam4/tradePost/TradePostService.java
#15 
어떤 변경 사항이 있나요?
질문 게시판, 거래 게시판의 PUT, DELETE API에서 발생했던 에러를 해결했습니다.
=> [#15] 게시판 기능 버그 수정 리팩토링

src/main/java/org/example/mjuteam4/comment/CommentController.java, src/main/java/org/example/mjuteam4/comment/CommentRepository.java, src/main/java/org/example/mjuteam4/comment/CommentService.java, src/main/java/org/example/mjuteam4/commentLike/CommentLikeController.java, src/main/java/org/example/mjuteam4/global/exception/ExceptionCode.java, src/main/java/org/example/mjuteam4/global/uitl/JwtUtil.java, src/main/java/org/example/mjuteam4/question/QuestionController.java, src/main/java/org/example/mjuteam4/question/QuestionService.java, src/main/java/org/example/mjuteam4/question/exception/QuestionAccessUnauthorized.java, src/main/java/org/example/mjuteam4/tradePost/TradePostController.java, src/main/java/org/example/mjuteam4/tradePost/TradePostService.java, src/main/java/org/example/mjuteam4/tradePost/exception/QuestionAccessUnauthorized.java
#19
어떤 변경 사항이 있나요?
- 질문 별 댓글 조회 기능 버그 해결
- jwtUtil을 이용한 접근 권한 체크 코드 각 API에 추가
=> [#19] 질문 별 댓글 조회 및 권한 체크 코드 추가

src/main/java/org/example/mjuteam4/disease/DiseaseController.java, src/main/java/org/example/mjuteam4/disease/DiseaseService.java, src/main/java/org/example/mjuteam4/disease/dto/Disease.java, src/main/java/org/example/mjuteam4/disease/dto/DiseaseRequest.java, src/main/java/org/example/mjuteam4/disease/dto/DiseaseResponse.java, src/main/java/org/example/mjuteam4/mypage/entity/Member.java
#21 
1. 기존 진단 기능에 dto, entity 추가
=> [#21] 기존 진단 기능에 dto, 엔티티 추가

src/main/java/org/example/mjuteam4/comment/dto/response/CommentResponse.java
#5
어떤 변경 사항이 있나요?
프론트 측에서 댓글 응답 구조에 좋아요를 눌렀는 지 안 눌렀는 지를 확인하는 boolean 값 요청.
이 요청을 댓글 응답 구조에 반영
단순 코드 리팩토링이므로 리뷰는 필요 없으 거 같습니다.
=> [#5] 프론트측 요구에 따른 댓글 응답 구조에 liked 추가

src/main/java/org/example/mjuteam4/disease/DiseaseController.java, src/main/java/org/example/mjuteam4/disease/DiseaseService.java
#26 
어떤 변경 사항이 있나요?
AI 응답 지연에 따라 서블릿 스레드가 긴 시간 점유되는 것을 막고자
식물 진단 API 비동기 처리하였습니다.
구조만 한 번 보시면 될 거 같습니다.
=> [#26] 식물 진단 API 컨트롤러 비동기 처리

build.gradle, src/main/java/org/example/mjuteam4/chatbot/config/ChatBotConfig.java, src/main/java/org/example/mjuteam4/chatbot/controller/ChatBotController.java, src/main/java/org/example/mjuteam4/chatbot/dto/ChatBotRequestDto.java, src/main/java/org/example/mjuteam4/chatbot/dto/ChatBotResponseDto.java, src/main/java/org/example/mjuteam4/chatbot/service/ChatBotService.java, src/main/resources/prompt.txt
#33 
어떤 변경 사항이 있나요?
1. SpringAI를 이용한 챗봇(GPT-40)
=> feat: 챗봇 api

src/main/java/org/example/mjuteam4/chatbot/controller/ChatBotController.java
> ex) #이슈번호, #이슈번호
어떤 변경 사항이 있나요?
> 작업 내용 및 변경 사항을 알려주세요. 어떻게보다 무엇을 왜 했는지 설명해주세요.
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> fix: 챗봇 api 메서드 get -> post 수정

src/main/java/org/example/mjuteam4/mypage/MyPageController.java, src/main/java/org/example/mjuteam4/mypage/MypageService.java, src/main/java/org/example/mjuteam4/mypage/dto/MemberResponse.java
=> feat: 유저 리스트 반환

src/main/java/org/example/mjuteam4/question/dto/response/QuestionResponse.java
#36
어떤 변경 사항이 있나요?
질문 리스트 응답에 유저 정보(username, memberId) 추가
=> fix: 질문 리스트 응답에 유저 정보 추가

src/main/java/org/example/mjuteam4/tradePost/dto/response/TradePostResponse.java
#32
어떤 변경 사항이 있나요?
거래 게시판 응답에 유저 정보 추가
=> fix: 거래 게시판 응답에 유저 정보 추가

src/main/java/org/example/mjuteam4/mypage/MyPageController.java, src/main/java/org/example/mjuteam4/plant/PlantController.java, src/main/java/org/example/mjuteam4/plant/PlantService.java
어떤 변경 사항이 있나요?
토큰 발급 api username넣어서 발급
> 작업 내용 및 변경 사항을 알려주세요. 어떻게보다 무엇을 왜 했는지 설명해주세요.
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> Refactor: 토큰 발급 username으로

src/main/java/org/example/mjuteam4/question/QuestionController.java, src/main/java/org/example/mjuteam4/question/QuestionRepository.java, src/main/java/org/example/mjuteam4/question/QuestionService.java, src/main/java/org/example/mjuteam4/tradePost/TradePostController.java, src/main/java/org/example/mjuteam4/tradePost/TradePostRepository.java, src/main/java/org/example/mjuteam4/tradePost/TradePostService.java
#44 
사용자 자신이 작성한 거래 게시글, 질문 게시글 모아보는 API 개발
=> feat: 멤버 별 게시글 조회

src/main/java/org/example/mjuteam4/question/QuestionController.java, src/main/java/org/example/mjuteam4/question/QuestionRepository.java, src/main/java/org/example/mjuteam4/question/QuestionService.java, src/main/java/org/example/mjuteam4/tradePost/TradePostController.java, src/main/java/org/example/mjuteam4/tradePost/TradePostRepository.java, src/main/java/org/example/mjuteam4/tradePost/TradePostService.java
#44 
어떤 변경 사항이 있나요?
개발 과정 중 실수를 수정했습니다
=> fix: api 개발 실수 수정

src/main/java/org/example/mjuteam4/question/QuestionController.java
=> fix: 두 번째 실수 수정

build.gradle, src/main/java/org/example/mjuteam4/global/uitl/JwtUtil.java, src/main/java/org/example/mjuteam4/mypage/MyPageController.java, src/main/java/org/example/mjuteam4/mypage/MypageService.java, src/main/java/org/example/mjuteam4/mypage/dto/TokenRequest.java, src/main/java/org/example/mjuteam4/plant/Plant.java, src/main/java/org/example/mjuteam4/plant/PlantController.java, src/main/java/org/example/mjuteam4/plant/PlantRepository.java, src/main/java/org/example/mjuteam4/plant/PlantService.java, src/main/java/org/example/mjuteam4/plant/dto/PlantCollectionResponse.java, src/main/java/org/example/mjuteam4/security/provider/TokenProvider.java
#43 
- 식물 도감 api 추가
- 토큰 username으로 생성 -> email로 생성 검증도 email로
- username은 변경될 수 있으므로 변경되지 않는 email로 하는것이 더 좋다고생각.
=> 식물 도감 & 토큰 생성 방식 수정

src/main/java/org/example/mjuteam4/global/result/ResultCode.java, src/main/java/org/example/mjuteam4/mypage/MyPageController.java, src/main/java/org/example/mjuteam4/mypage/MypageService.java, src/main/java/org/example/mjuteam4/mypage/entity/Member.java
> ex) #이슈번호, #이슈번호
어떤 변경 사항이 있나요?
유저 프로필 사진 등록 API
=> Feat: 유저 사진 등록 API

src/main/java/org/example/mjuteam4/chat/config/StompWebSocketConfig.java, src/main/java/org/example/mjuteam4/security/filter/TokenAuthenticationFilter.java
=> fix: 웹소켓 연결 관련 설정

src/main/java/org/example/mjuteam4/mypage/MypageService.java, src/main/java/org/example/mjuteam4/mypage/dto/MyPlantListResponse.java, src/main/java/org/example/mjuteam4/mypage/dto/RegisterMyPlantRequest.java, src/main/java/org/example/mjuteam4/mypage/entity/MyPlant.java, src/main/java/org/example/mjuteam4/plant/PlantRepository.java
#65
내 식물 도감 번호로 등록
내 식물 조회에 도감 사진 추가
=> 내 식물 등록 관련 수정 및 response 필드 추가

src/main/java/org/example/mjuteam4/chat/service/ChatService.java
> ex) #이슈번호, #이슈번호
어떤 변경 사항이 있나요?
> 작업 내용 및 변경 사항을 알려주세요. 어떻게보다 무엇을 왜 했는지 설명해주세요.
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> fix: 채팅 에러 수정

src/main/java/org/example/mjuteam4/chat/config/StompWebSocketConfig.java
> ex) #이슈번호, #이슈번호
어떤 변경 사항이 있나요?
> 작업 내용 및 변경 사항을 알려주세요. 어떻게보다 무엇을 왜 했는지 설명해주세요.
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> fix: handshake handler 제거
